// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"conduit/cmd/conduit-admin/conf"
	"conduit/internal/biz/manager"
	"conduit/internal/data"
	"conduit/internal/server"
	"conduit/internal/service"
	"conduit/internal/service/plugin"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "conduit/internal/plugins/register"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, etcd *conf.Etcd, logger log.Logger) (*kratos.App, func(), error) {
	unitWatcher := data.NewUnitWatcher(etcd, logger)
	managerManager := manager.NewManager(unitWatcher, logger)
	conduitServer := service.NewConduitServer(logger, managerManager)
	pluginAdminServer := plugin.NewPluginAdminServer()
	adminServer := server.NewAdminHTTPServer(confServer, logger, conduitServer, pluginAdminServer)
	app := newApp(logger, adminServer)
	return app, func() {
	}, nil
}
