// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"conduit/internal/conf"
	"conduit/internal/data"
	"conduit/internal/model"
	"conduit/internal/server"
	"conduit/internal/service/application"
	"conduit/internal/service/plugin"
	"conduit/internal/service/router"
	"conduit/internal/service/workflow"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "conduit/internal/plugins/register"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, etcd *conf.Etcd, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	pluginAdminServer := plugin.NewPluginAdminServer(dataData)
	applicationRepo := model.NewApplicationRepo(dataData)
	applicationAdminServer := application.NewApplicationAdminServer(applicationRepo)
	routerRepo := model.NewRouterRepo(dataData)
	routerAdminServer := router.NewRouterAdminServer(routerRepo)
	workflowRepo := model.NewWorkflowRepo(dataData)
	workflowAdminServer := workflow.NewWorkflowAdminServer(workflowRepo)
	adminServer := server.NewAdminHTTPServer(confServer, logger, pluginAdminServer, applicationAdminServer, routerAdminServer, workflowAdminServer)
	app := newApp(logger, adminServer)
	return app, func() {
		cleanup()
	}, nil
}
