// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"conduit/internal/biz/manager"
	"conduit/internal/conf"
	"conduit/internal/data"
	"conduit/internal/server"
	"conduit/internal/service"
	"conduit/internal/service/plugin"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "conduit/internal/plugins/register"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, etcd *conf.Etcd, logger log.Logger) (*kratos.App, func(), error) {
	unitWatcher := data.NewUnitWatcher(etcd, logger)
	managerManager := manager.NewManager(unitWatcher, logger)
	conduitServer := service.NewConduitServer(logger, managerManager)
	httpServer := server.NewHTTPServer(confServer, logger, conduitServer)
	pluginServer := plugin.NewPluginServer()
	serverConduitServer := server.NewConduitHTTPServer(confServer, logger, pluginServer)
	app := newApp(logger, httpServer, serverConduitServer, managerManager)
	return app, func() {
	}, nil
}
