// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"conduit/internal/conf"
	"conduit/internal/server"
	"conduit/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	conduitServer := service.NewConduitServer(logger)
	httpServer := server.NewHTTPServer(confServer, logger, conduitServer)
	pluginServer := service.NewPluginServer()
	adminServer := server.NewAdminHTTPServer(confServer, logger, conduitServer, pluginServer)
	app := newApp(logger, httpServer, adminServer)
	return app, func() {
	}, nil
}
